const data =
{
    id: 1,
    name: 'joleene steffen',
    occupation: 'owner',
    img: '../src/images/homeBkg.jpg',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, facilis repellat. Nemo tempora aut animi! Adipisci, commodi quam ipsum sed, dolores accusamus maiores soluta distinctio illo laudantium asperiores enim a. Molestiae error deserunt nesciunt veniam esse iste magni sed pariatur, natus repudiandae placeat nisi asperiores, aperiam facere ratione culpa! Corrupti dolor voluptates, nam quae velit deserunt? Temporibus tenetur doloremque maiores magni eum rem deleniti recusandae asperiores, adipisci iusto corporis dolor odit provident aperiam natus possimus harum facere, enim minus facilis optio? Ad provident maiores id adipisci quos minus, delectus quod sit officia ullam deserunt dolores accusamus voluptates ducimus nulla earum commodi facilis sed fuga necessitatibus. Aperiam, quam reiciendis? Fuga molestiae perspiciatis iste error atque rerum nostrum quae ab recusandae in, minima voluptas reprehenderit laborum quidem, enim quaerat odio nisi veniam? Assumenda non, magni similique itaque maiores, quo soluta suscipit obcaecati, expedita architecto cupiditate dolorem ipsa doloribus beatae modi saepe inventore quasi qui minus blanditiis dolor quas neque! Consequuntur quas sequi quod ullam, animi laboriosam, quia maiores officia eius, earum iure sapiente! Iure enim quibusdam vel error tempora facere assumenda! Eum ipsa minus placeat minima, sunt velit. Debitis, iste error officia suscipit fuga a. Provident cumque voluptas quam at ut, mollitia error doloribus laboriosam ipsum nisi quae reprehenderit quasi repellendus aut facilis itaque iure, vitae vel nemo odio aspernatur? Expedita deleniti repellendus dignissimos sunt, temporibus quasi soluta dicta autem voluptas nobis fugit fugiat enim odit praesentium, ullam harum nulla veritatis? Itaque minima eligendi tempora labore et harum tenetur vitae, eveniet a, aperiam voluptates fugit odio ea, laboriosam aliquid culpa! Iusto temporibus vel magni distinctio non, nulla atque asperiores praesentium reiciendis quos sequi. Nulla numquam sunt minus sit iure consectetur! Nam, qui accusamus, assumenda nihil et impedit, deserunt temporibus ipsum sint repellendus sit! A, possimus unde. Sapiente exercitationem totam adipisci tempore itaque!',
};
export default data;
