const data = [
  {
    id: 1,
    title: 'trees',
    category: 'landscape',
    price: 255.99,
    img: '../src/images/landscape1.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'fields',
    category: 'landscape',
    price: 223.99,
    img: '../src/images/homeBkg.jpg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'feeding time',
    category: 'animals',
    price: 196.99,
    img: '../src/images/homeBkg.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'cow',
    category: 'animals',
    price: 200.99,
    img: './images/animals2.jpg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'river',
    category: 'landscape',
    price: 202.99,
    img: './images/landscape4.jpg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'waterlily',
    category: 'flowers',
    price: 180.99,
    img: './images/flower1.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'plant',
    category: 'flowers',
    price: 230.99,
    img: './images/flower2.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'color overflow',
    category: 'flowers',
    price: 120.99,
    img: './images/flower3.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'country delight',
    category: 'landscape',
    price: 196.99,
    img: './images/landscape5.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default data;
